### PR TITLE
Update to upstream master

### PR DESCRIPTION
**Pull request by filipebarros**
As things stand, our master branch is 8 commits behind the upstream repository. This fixes it. Doing this should solve https://hakiri.io/technologies/omniauth-saml/issues/b0dc4bb2f4b430

The plan is to merge this into our master branch and then rebase `fix/force-logout-response-soft-validation` on top of it.

### CODE REVIEW

**Review by ADolhov — APPROVED** [review]

**Comment by filipebarros** [comment]
Added a few people to the review list. We should create GitHub team handles so we can include everyone from a team when something needs to be reviewed by a specific team

**Comment by coertzec** [comment]
Do we know why we're using our own version of the gem? Might be possible to move to the public version.

**Comment by filipebarros** [comment]
https://github.com/Fuseit/omniauth-saml/commit/18d31a052b6ad15c98eaed825185ce24e067ce90 we're using this commit, which I don't think is in the main version: https://github.com/omniauth/omniauth-saml/blob/a0eedd6e2daf9fe6285622d4d635aca165358dce/lib/omniauth/strategies/saml.rb#L169

**Comment by filipebarros** [comment]
I investigated a bit: it turns out that by default, `ruby-saml` sets that value to `true`, but `omniauth-saml` actually enforces that to `false`. One option would be to try and extend it on `omniauth-saml` to accept a value via the initializer:

```ruby
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :saml,
    soft: true
end
```

**Review by ACronje — APPROVED** [review]

**Review by coertzec — APPROVED** [review]
Make sure to test SSO before merging this

**Review by korki — APPROVED** [review]
What he said ^

**Comment by filipebarros** [comment]
@ADolhov the issue that led us to create our own fork is reproducible in any way? Does it happen to all clients or does it happen randomly? If we have a way to reproduce it, we might be able to test the usage of the actual gem instead of the fork...

**Review by alastairp — APPROVED** [review]

**Pull request closed without merging**
